### ISSUE TITLE
BAG-API v2 nummeraanduidingen

### ISSUE THREAD

**Issue by rogiernota** [lvbag/BAG-API#11]
When searching for "nummeraanduidingen" with "postcode" and "huisnummer" as query parameters  the response seems to contain all "nummeraanduidingen" within the supplied "postcode". It seems that the results are not filtered on the "huisnummer". Adding "exacteMatch" as query parameter with value "true" does not seem to have any effect on the response.

**Comment by lvbag** [comment]
This functionality is not implemented in test yet.
The response you are getting is probably a test for the implementation for paging.
