### ISSUE TITLE
Internal Server Error on requesting a POST to /panden

### ISSUE THREAD

**Issue by roland-d** [lvbag/BAG-API#13]
Hello,

I am trying to get the REST API calls to work but struggling a bit. Importing the endpoints into Postman goes without a problem. I am trying to access this URL via a POST:
`https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/panden?geldigOp=2020-01-01`

I have set the following headers that need to be filled in:
- X-Api-Key with my API key
- Content-Crs: `epsg:28992`
- Accept-Crs: `epsg:28992`

On sending the request I get the following output:
```
{"status":500,"title":"Interne server fout.","type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","detail":"Internal server error.","instance":"https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/panden?geldigOp=2020-01-01","code":"serverError"}
```

Is there something wrong with the request I am sending or is this endpoint broken?

What does work is a GET to `https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/panden/0202100000236146` and the header `Accept-Crs` set to `epsg:28992`.

Is the test environment limited to epsg 28992 or are there other options?

Thank you.

**Comment by lvbag** [comment]
Hi Roland,
It is necessary to add a ID in this request.

for example:
https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/panden/0268100000000625?geldigOp=2020-01-01

Nicole

**Comment by roland-d** [comment]
Hello Nicole,

Thank you for your reply. That URL is for the GET request I think and I am trying the POST. The GET request with the ID works for me.

What I forgot to mention that with the POST you need to send the geometric details which I have done as:
```
{
    "coordinates": [
        "51.8602477",
        "4.3615441"
    ],
    "type": "Pand"
}
```
What is unclear to me is the `type`. I chose `Pand` here because I am requesting the `/panden` endpoint. Is there some documentation of which types are expected here?

**Comment by lvbag** [comment]
Hi Roland,
This endpoint is not yet implemented in test. Even if you are doing everything right, you won't get a response.

The type is the type of geometry. 
In the yaml specs it says:

{
  "type": "Point",
  "coordinates": [
    0
  ]
}

The specs are published under:
https://github.com/lvbag/BAG-API/tree/master/Technische%20specificatie. 

For a swagger version you can follow the link on:
https://github.com/lvbag/BAG-API

Nicole

**Comment by roland-d** [comment]
Hello Nicole,

Thank you for the quick reply. The Swagger endpoints I have loaded into Postman, that is very useful. Although some of the descriptions are a bit cryptic to me but that may be more me than the documentation :)

> This endpoint is not yet implemented in test.
That explains everything then. What I would like to recommend is to return an HTTP status of 501 Not Implemented for those endpoints not yet implemented. That will help us users know what the status is of the endpoint.

**Comment by lvbag** [comment]
Hi Roland, 
We are aware of that. One of the points we would like to improve.
For now you can find the status in the releasenotes.
Nicole
