### ISSUE TITLE
Ophalen adres doormiddel van postcode huisnummer?

### ISSUE THREAD

**Issue by woodsbox** [lvbag/BAG-API#15]
Het is voor mij niet duidelijk via welke service dit gedaan kan worden?

**Comment by lvbag** [comment]
Dit endpoint is nog niet geimplementeerd en is daarom nog niet terug te vinden. De bevraging zal waarschijnlijk onderdeel uit gaan maken van het /adresssen enpoint.

**Comment by woodsbox** [comment]
Enig idee op welk termijn die geïmplementeerd gaat worden?

**Comment by lvbag** [comment]
We verwachten dit in ongeveer in november te realiseren
