### ISSUE TITLE
GET resulteert in http error 400 response

### ISSUE THREAD

**Issue by bspiering** [lvbag/BAG-API#17]
Een GET via Postman of cURL resulteert bij mij altijd in een http error 400 response.
Ik heb diverse GET voorbeelden uit de Swagger UI geprobeerd, bijvoorbeeld:
https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/woonplaatsen/2096
of:
https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/woonplaatsen/2096?geldigOp=2020-09-24
Met header: -H  "accept: application/hal+json" -H  "X-Api-Key: <mijn Api Key van 64 tekens>

Wat gaat er verkeerd?

**Comment by strijm** [comment]
De URI's zijn correct, daar kan het niet aan liggen. Om uit te sluiten dat het aan een verkeerde API key ligt: kunt u laten weten van welke organisatie u bent?

**Comment by bspiering** [comment]
Ik ben van Sweco.

Van: Mark Strijker <notifications@github.com>
Verzonden: vrijdag 25 september 2020 10:48
Aan: lvbag/BAG-API <BAG-API@noreply.github.com>
CC: Spiering, Boudewijn <Boudewijn.Spiering@sweco.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [lvbag/BAG-API] GET resulteert in http error 400 response (#17)


De URI's zijn correct, daar kan het niet aan liggen. Om uit te sluiten dat het aan een verkeerde API key ligt: kunt u laten weten van welke organisatie u bent?
