### ISSUE TITLE
Ondersteuning geometrie en geometrisch zoeken

### ISSUE THREAD

**Issue by kimvw** [lvbag/BAG-API#2]
Momenteel is de geometrie van het Verblijfsobject leeg, en is het niet mogelijk op basis van een geometrie te zoeken. Geometrie wordt waarschijnlijk qua consumer aanmaken en data verwerken nog een lastig stuk. Het zou daarom fijn zijn om voor de genoemde punten snel een eerste werkend voorbeeld te hebben.

**Comment by NicoleKortoomsBAG** [comment]
Geometrie is inmiddels geimplementeerd
