### ISSUE TITLE
Opvragen lijst van woonplaatsen

### ISSUE THREAD

**Issue by Tux** [lvbag/BAG-API#21]
Voor validatie is het wenselijk om (op peildatum) een lijst van geldige woonplaatsen te hebben.
Het kadaster heeft in het verleden deze lijsten als CSV beschikbaar gesteld (met `;` als scheidingsteken i.p.v. `,`, maar daar kan ik mee leven):
```
$ head -3 24-04-2012\ WPL\ overzicht\ gemeenten.csv
Woonplaats;Woonplaats code;Ingangsdatum WPL;Einddatum WPL;Gemeente;Gemeente code;Ingangsdatum nieuwe gemeente;Gemeente beeindigd per
 't Goy;2054;;;Houten;0321;;
 't Haantje;2164;;;Coevorden;0109;;
```
Zijn er plannen om deze **complete** lijst als CSV of JSON op te kunnen vragen (evt op peildatum)?

**Comment by lvbag** [comment]
Hallo Tux,
Op dit moment is het niet voorzien deze lijst als API te leveren. Een Gemeente-Woonplaats relatietabel wordt bij het BAG extract geleverd in XML formaat. Als u contact opneemt op bag@kadaster.nl, helpen we u verder.

**Comment by Tux** [comment]
Dan haal ik die wel op van https://opendata.cbs.nl/statline/#/CBS/nl/dataset/84734NED/table?ts=1602593579537
Jammer. Gemiste kans
