### ISSUE TITLE
Bestandsindeling op GitHub

### ISSUE THREAD

**Issue by kimvw** [lvbag/BAG-API#3]
Onder technische specificatie staan meerdere versies en ZIP-bestanden van de API. Liever zie ik in Git geen ZIP-bestanden. Versienummers in bestanden is ook niet handig, aangezien GIT al voor het versiebeheer zorgt. Een enkele map met specificaties zou beter zijn.

**Comment by lvbag** [comment]
Beide opties zijn beschikbaar gemaakt.
