### ISSUE TITLE
With Google Maps

### ISSUE THREAD

**Issue by chithract** [lvbag/BAG-API#35]
Hi,

Can we link bag viewer with Google maps?

Thanks,
Chithra

**Comment by NicoleKortoomsBAG** [comment]
The BAG viewer uses the tiles provided by PDOK, a Kadaster Service, there is no way for the end user to switch to another tile provider. 
The viewer is a user interface. For developing your own services with BAG data there are other products like BAG extract or the BAG API Individuele Bevragingen depending on  your implementation. The 'beslisboom' can help you make a choice. It is in Dutch. If that is a problem, you can contact the customer service of the BAG. [contact_bag](https://formulieren.kadaster.nl/contact_bag)
