### ISSUE TITLE
Verbinding tussen adressen en adresseerbare objecten

### ISSUE THREAD

**Issue by rjzondervan** [lvbag/BAG-API#36]
Goedenmiddag!

Op verzoek van de gemeente 's-Hertogenbosch ben ik bezig om de software onder verhuizen.s-hertogenbosch.nl aan te passen om te functioneren met de BAG v2 API.
Ik loop nu echter tegen het punt aan dat waar de v1 API een link opgaf van de nummeraanduiding van een object naar een adresseerbaar object (hetzij ligplaats, standplaats of verblijfsobject), maar dat de nieuwe API deze link niet opgeeft. Ik zie echter de verbinding wel andersom aanwezig zijn.

Is er een manier waarop we met de identificatie van de nummeraanduiding meer informatie over het adresseerbare object kunnen ophalen?

**Comment by NicoleKortoomsBAG** [comment]
Goedemiddag,
Ja dat kan. 
Met de volgende bevraging kun je het adressseerbaarobject van een nummeraanduiding bevragen:
https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2/adresseerbareobjecten?nummeraanduidingIdentificatie=[NUMID]
Voor de testomgeving:
https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/adresseerbareobjecten?nummeraanduidingIdentificatie=[NUMID]

**Comment by rjzondervan** [comment]
Top, bedankt voor de snelle reactie! Deze heb ik in de documentatie over het hoofd gezien.
