### ISSUE TITLE
Issue met genereren C# client in NSwagStudio

### ISSUE THREAD

**Issue by kimvw** [lvbag/BAG-API#4]
Issue is gemeld bij NSwagStudio:
https://github.com/RicoSuter/NSwag/issues/2576

Nog niet duidelijk of dit komt door een verkeerde tool, of een verkeerde definitie. Voor mij is het vreemd dat er op gedeelde Headers al wordt aangegeven of deze verplicht of optioneel is.

**Comment by NicoleKortoomsBAG** [comment]
Kan dit ticket gesloten worden?
