### ISSUE TITLE
Vraag: Informatie model BAG in EAP(X) formaat

### ISSUE THREAD

**Issue by arthur-edsn** [lvbag/BAG-API#41]
Vanuit de energie sector zijn we aan het kijken hoe we het Informatie Model van het BAG (individuele bevragingen) kunnen gebruiken als referentie model. In de documentatie zie ik een aantal screenshots van Enterprise Architect (IMBAG - Conceptueel model). Ik wil vragen of er een mogelijkheid bestaat om dit Enterprise Architect bestand beschikbaar te stellen in deze repository. 

Het doel is om in te kunnen zien hoe bijvoorbeeld het datatype 'AN' (alfanummeriek) opgebouwd is, of hoe een VlakOfMultivlak datatype er uit ziet.

**Comment by strijm** [comment]
Het Enterprise Architect bestand zelf kunnen we niet beschikbaar stellen via de repository omdat deze in beheer is bij het Kadaster.
In de BAG Catalogus 2018 is te vinden welke attributen in het IMBAG 2.0 van welk type zijn (bv. AN of VlakOfMultivlak).
Op de Kadaster schema's pagina's (https://developer.kadaster.nl/schemas/-/categories/2652558) zijn de XML Schema definitie voor het bronhouder koppelvlak te vinden. In het bestand lvbag-types_v2_0_0.xsd staan de types AN en VlakOfMultivlak gedefinieerd. Dit is zoals de informatie wordt aangeleverd door de bronhouders.
Voor afnemers van BAG informatie is er o.a. de BAG Individuele Bevragingen API. Via de URI: https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2/openapi.yaml is de OAS v3 specificatie te vinden. Hierin staan ook alle attributen gespecificeerd met dezelfde definitie als in het bronhouder koppelvlak, met dit verschil dat het type AN hier niet voorkomt. De attributen die van het type AN zijn in het IMBAG 2.0 hebben echter wel dezelfde definitie in de OAS v3 specificatie.
Evt. is het ook mogelijk om een XML export te maken uit het Enterprise Architect model.
