### ISSUE TITLE
Losse YAML definities

### ISSUE THREAD

**Issue by kimvw** [lvbag/BAG-API#5]
Momenteel zijn er losse definities voor de verschillende objecttypes. Liever zien we een enkele definitie/Api voor de 7 objecttypes in de BAG. Dit scheelt in het genereren van consumers.

**Comment by lvbag** [comment]
Hallo Kim,
Er is gekozen voor de losse definities in verband met de beheerbaarheid van de API en het voorkomen van bugs in de toekomst. Helaas is dit een bijeffect.
