### ISSUE TITLE
Ophalen van verblijfsobjecten uit nummeraanduiding endpoint

### ISSUE THREAD

**Issue by Burkle1907** [lvbag/BAG-API#50]
v1 haalde verblijfsobjecten op uit de nummeraanduidingen, v2 doet dit niet. Is hier een workaround voor dat ik dit alsnog kan ophalen?

**Comment by NicoleKortoomsBAG** [comment]
Met het endpoint v2/adresseerbareobjecten?nummeraanduidingIdentificatie=<NUMID> kunt u dit doen.

Omdat het vanuit een nummeraanduiding niet duidelijk is om welk type adresseerbaarobject het gaat, is ervoor gekozen om deze functionaliteit niet te beperken tot alleen verblijfsobjecten, maar alle adresseerbare objecten inclusief lig- en standplaatsen
