### ISSUE TITLE
Woningtype uit API halen

### ISSUE THREAD

**Issue by luuklinc** [lvbag/BAG-API#53]
Hi,

Momenteel ben ik bezig met het ontwikkelen van een tool die gebruik maakt van deze API, maar ik vroeg mij af hoe ik het woningtype kan extraheren uit deze API.

Groet,

Luuk

**Comment by NicoleKortoomsBAG** [comment]
Hallo Luuk,
De BAG bevat geen woningtype. 
De API levert deze dus niet.
Groeten Nicole
