### ISSUE TITLE
Zoeken op zoekresultaat identificatie bij /adressen resulteert niet altijd tot een uitgebreide adres informatie

### ISSUE THREAD

**Issue by sky007** [lvbag/BAG-API#54]
Tijdens zoeken van adressen met de enpoint "/adressen/zoeken" met des betreffende parameters dat opgegeven kan worden. Krijg je een lijst met adressen met een omschrijving, identificatie en een uri.

![screenshot-1](https://user-images.githubusercontent.com/1032882/158774045-b5f41666-1790-4b90-b70d-552112f2463a.PNG)

Nadat je de identificatie heb kan je een uitgebreide details opvragen van een adres "/adressen", maar bij de volgende screenshot zie je dat een identificatie dat wel bestaat bij de zoekresultaat geen uitgebreide details van het adres kan krijgen.

![screenshot-3](https://user-images.githubusercontent.com/1032882/158774358-2e9f181f-7b81-4564-a157-f39671003461.PNG)

Als je zoekt op postcode & huisnummer dan kan je dat juist wel ophalen, dit is incorrect neem ik aan? Het kan ook zijn dat sommige via identificatie en postcode & huisnummer niet te vinden is met een huisletter.

**Comment by NicoleKortoomsBAG** [comment]
Hallo Sky007,
De acceptatieomgeving van de API bevat een kopie van begin 2018. Echter de zoekfunctionaliteit van diezelfde API op de accepatieomgeving maakt gebruik van een andere dienst die actuele data levert. Hierdoor is het mogelijk dat er een adres wordt gevonden dat geen onderdeel blijkt uit te maken van de testset. In dit geval is dat ook zo. Het adres is medio 2018 ontstaan. 
Wanneer je dezelfde vraag in de productieomgeving stelt, ontvang je wel de detailinformatie.

**Comment by sky007** [comment]
Hallo NicoleKortoomsBAG,

Duidelijk antwoord, dus in productie zal die nooit gebeuren ga ik dan ervan uit.
Als dat zo is dan sluit ik dit issue.
