### ISSUE TITLE
v1 of v2 

### ISSUE THREAD

**Issue by bosmaneelco** [lvbag/BAG-API#6]
Ik heb de BAG-API v2 even bekeken en aangeroepen vanuit Excel
en heb volgende vraag:

1.) Als ik nu iets wil ontwikkelen en wil kunnen zoeken op adres/postcode, kan ik dit al met v2 doen?

2.) Bevat de testomgeving een volledige dataset of is dit een subset?

Dank,

Eelco

**Comment by NicoleKortoomsBAG** [comment]
Hallo Eelco,
Op dit moment is alleen het zoeken op id nog beschikbaar in de testomgeving. De andere bevragingen worden nog verwacht. 
De testomgeving is gelinkt naar een volledige kopie van de database van Q1 2018.
Groeten Nicole
