### ISSUE TITLE
BAG acceptatie omgeving 

### ISSUE THREAD

**Issue by aevers1967** [lvbag/BAG-API#85]
de volgende url is niet meer beschikbaar:  https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/

**Comment by ElmerKnol** [comment]
Dat is correct. Per 2 april is de test (acceptatie) omgeving uitgezet. Testen kunnen, wanneer nodig, gewoon op de productie omgeving worden uitgevoerd.
