### ISSUE TITLE
Given attribute '_links.last.href' points to non existing or empty pages

### ISSUE THREAD

**Issue by DavidM-SV** [lvbag/BAG-API#88]
**1**
Send the following get request:
https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2/adressen?pageSize=100&page=1&expand=true&q=Maarssen

**2**
Got the following value for attribute __links.last.href_ in the response body after above get request:
https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2/adressen?pageSize=100&expand=true&q=Maarssen&page=198

->Note that the value for the page key = 198

**3**
I expected an array with data as value for the _embedded attribute in the response body for the following get request:
https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2/adressen?pageSize=100&expand=true&q=Maarssen&page=198

but instead got only this resonse (paste of entire response body) (->Note that the value for the page key = 198):
{
    "_links": {
        "self": {
            "href": "https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2/adressen?pageSize=100&page=198&expand=true&q=Maarssen"
        }
    }
}

**4**
The above is valid for api requests with values of 102 and higher as value for the page key

**Comment by KimChessaBAG** [comment]
Dear Sir/Madam,

Thank you very much for your message in which you indicate that the API returns empty pages after 100 bodies. Our API is not intended for bulk queries. The name of the API already says it all. You can use the API to perform "Individual queries". However, I can imagine that you have specific needs for retrieving these addresses. Therefore, we would like to think along with you and explore which alternative products might suit you better. Could you please provide a more detailed description of the data you are looking for and how(for example which format) you would like to retrieve it? And could you send this to BAG@kadaster.nl?

Kind regards, 
Kim Chessa
Functioneel beheerder BAG
